# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://devops12.com
date_format: "ordinal"
title: DevOps12
subtitle: "博客"
description: "谐云科技博客"
keywords: 谐云科技博客
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Huan Wei
organization: HarmonyCloud, Inc.
organization_url: http://www.harmonycloud.cn
location: Hangzhou, China
email: huanwei@harmonycloud.cn

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#  -
 #   href: /wiki/
  #  label: 维基

#  -
 #   href: /links/
  #  label: 链接

 # -
  #  href: /about/
   # label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: huanwei/huanwei.github.io

# ---------------- #
#      Socials     #
# ---------------- #
github_username: huanwei
#douban_username: freedim
#facebook_username: mzlogin
#weibo_username: mzlogin
#zhihu_username: mzlogin
#twitter_username: mzlogin

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
#comments_provider: disqus
#duoshuo_username: mazhuang
#disqus_username: mzlogin
# 在使用 disqus 的时候可点击显示多说评论框
#lazy_load_duoshuo: true

# ---------------- #
#    Analytics     #
# ---------------- #
#google:
 #   analytics_id: UA-80669434-1

# ---------------- #
#      Datas       #
# ---------------- #
#skill_software_keywords: [Java, C++, Python, Design Patterns]
#skill_mobile_app_keywords: [Android, Reverse Engineering]
#skill_windows_keywords: [Win32 SDK, DuiLib, WTL, COM, WinDbg]
